In [4]:
from random import randint
from random import random
from random import seed
import numpy as np

In [5]:
alpha = float(0.0001)
epsilon = float(0.1)
gamma = float(0.8)
numTraining = int(20)
w = [0.5,0.2, 0.1, 0.1]
np.set_printoptions(linewidth=120)


In [6]:
#this function get the next row and colume based on the policy with probability 0.8
#and perpendicular on the policy with probability 0.2

#if the function will take the perpendicular direction
#it will choose the either of the two perpendicular direction on 50% probability
def get_next_r_c(r, c):
    prob = random()
    #80% of the time will take the policy action
    if prob <= 0.8: 
        if policy[r][c] == 'up':
            rnext = r - 1
            cnext = c
        elif policy[r][c] == 'left':
            rnext = r
            cnext = c - 1
        elif policy[r][c] == 'right':
            rnext = r
            cnext = c + 1
        elif policy[r][c] == 'down':
            rnext = r + 1
            cnext = c
            
    #20% of the time will make a perpendiclar action on the policy action
    else:
        if policy[r][c] == 'up' or policy[r][c] == 'down':
            prob2 = random()
            if prob2>0.5:
                #left
                rnext = r
                cnext = c - 1
            else:
                #right
                rnext = r
                cnext = c + 1
                
        elif policy[r][c] == 'right' or policy[r][c] == 'left':
            prob2 = random()
            if prob2>0.5:
                #up
                rnext = r - 1
                cnext = c
            else:
                #down
                rnext = r + 1
                cnext = c
                
    return rnext, cnext

In [7]:
def recursive_approximation(r, c):
    #updates delta values recursively for each step
    if policy[r][c] == 'exit':
        if positive_reward_position_row == r and positive_reward_position_col == c:
            return 1
        else:
            return -1
    
    rnext, cnext = get_next_r_c(r, c)
    
    while rnext >= rows or rnext < 0 or cnext >= cols or cnext < 0 or policy[rnext][cnext] == 'obstacle':
        rnext, cnext = get_next_r_c(r, c)
    
    value = recursive_approximation(rnext,cnext) + one_step_reward
    delta_rule(r,c, value)
    return value

In [8]:
def approximate_value(r,c):
    #gets approximate value based on current weights
    if negatives:
        return w[0]+w[1]*c+w[2]*r+w[3]*get_distance(r,c, True)+w[4]*get_distance(r,c, False)
    else:
        return w[0]+w[1]*c+w[2]*r+w[3]*get_distance(r,c,True)

In [9]:
import math
def get_distance(r,c,positive):
    #Gets distance between goal and current position
    if positive:
        return math.sqrt((r-positive_reward_position_row)**2+(c-positive_reward_position_col)**2)
    else:
        return math.sqrt((r-negative_reward_position_row)**2+(c-negative_reward_position_col)**2)


In [10]:
def delta_rule(r,c, current_observed_value):
    #updates current weights
    w[0] = w[0] + alpha * (current_observed_value - approximate_value(r,c))
    w[1] = w[1] + alpha * (current_observed_value - approximate_value(r,c)) * c
    w[2] = w[2] + alpha * (current_observed_value - approximate_value(r,c)) * r
    w[3] = w[3] + alpha * (current_observed_value - approximate_value(r,c)) * get_distance(r,c, True)
    #If fifth feature is needed
    if negatives:
            w[4] = w[4] + alpha * (current_observed_value - approximate_value(r,c)) * get_distance(r,c, False)


In [11]:
def function_approximation():
    # runs function approximation
    for i in range(iterations):
        r = randint(0, rows - 1)
        c = randint(0, cols - 1)
        while policy[r][c] == 'obstacle' or policy[r][c] == 'exit':
            r = randint(0, rows - 1)
            c = randint(0, cols - 1)
        recursive_approximation(r, c)



In [12]:
def view_utility_map():
    # shows the utility map
    utility_map = np.zeros((rows,cols))
    for r in range(rows):
        for c in range(cols):
            if policy[r][c] != 'obstacle':
                utility_map[r,c] = approximate_value(r,c)
    print(utility_map)

In [15]:
iterations = 10000
w = [0.5,0.2, 0.1, 0.1, 0.1]
#should be read it from outside file
policy = [
    ['right', 'right',    'right', 'exit'],
    ['up',    'obstacle', 'up',    'exit'],
    ['up',    'left',     'up',  'left']
]
negatives = True #Enables 5th feature which adds distance to negative goals
utility_map = []
positive_reward_position_row = 0
positive_reward_position_col = 3
negative_reward_position_row = 1
negative_reward_position_col = 3
rows = len(policy)
cols = len(policy[0]) 
one_step_reward = -0.04
function_approximation()
view_utility_map()

# print(w)

[[0.90993872 0.87348418 0.85139396 0.8854148 ]
 [0.76803006 0.         0.67391915 0.62524369]
 [0.66980588 0.63256612 0.60903972 0.64036913]]


In [19]:
iterations = 10000
w = [0.5,0.2, 0.1, 0.1]
policy = [
    ['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'exit' ],
    ['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'up'   ],
    ['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'up'   , 'up'   ],
    ['right', 'right', 'right', 'right', 'right', 'right', 'right', 'up',    'up'   , 'up'   ],
    ['right', 'right', 'right', 'right', 'right', 'right', 'up'   , 'up',    'up'   , 'up'   ],
    ['right', 'right', 'right', 'right', 'right', 'up'   , 'up'   , 'up',    'up'   , 'up'   ],
    ['right', 'right', 'right', 'right', 'up'   , 'up'   , 'up'   , 'up',    'up'   , 'up'   ],
    ['right', 'right', 'right', 'up'   , 'up'   , 'up'   , 'up'   , 'up',    'up'   , 'up'   ],
    ['right', 'right', 'up'   , 'up'   , 'up'   , 'up'   , 'up'   , 'up',    'up'   , 'up'   ],
    ['right', 'up',    'up'   , 'up'   , 'up'   , 'up'   , 'up'   , 'up',    'up'   , 'up'   ]
]
utility_map = []
negatives = False

positive_reward_position_row = 0
positive_reward_position_col = 9

rows = len(policy)
cols = len(policy[0]) 


one_step_reward = -0.04
function_approximation()

view_utility_map()


[[0.55913501 0.60886205 0.6585891  0.70831614 0.75804318 0.80777022 0.85749727 0.90722431 0.95695135 1.00667839]
 [0.50862183 0.55840215 0.60819749 0.65801519 0.70786827 0.75778203 0.80781275 0.85811184 0.90921993 0.96348819]
 [0.4589519  0.50888567 0.55887551 0.60894711 0.65914401 0.70954529 0.76030661 0.81176147 0.86464868 0.920298  ]
 [0.41008146 0.46025171 0.51053514 0.56097874 0.61165736 0.66269493 0.714303   0.76684346 0.82088644 0.8771078 ]
 [0.36194546 0.41241218 0.46305389 0.51393483 0.56515049 0.61684454 0.66923177 0.72261898 0.77739257 0.8339176 ]
 [0.31446644 0.36526603 0.41629814 0.46763708 0.51938608 0.57168734 0.62473105 0.67875455 0.73401564 0.79072741]
 [0.26756305 0.31871146 0.37014049 0.42192762 0.47417393 0.52700852 0.58058927 0.63509449 0.69069942 0.74753721]
 [0.22115641 0.27265402 0.32446915 0.37667733 0.42937183 0.48266443 0.53668252 0.59155973 0.64741856 0.70434701]
 [0.17517413 0.22701069 0.27919087 0.33178515 0.38487657 0.43855956 0.49293594 0.54810674 0.6041

In [12]:
iterations = 10000
w = [0.5,0.2, 0.1, 0.1]
negatives = False

policy = [
    ['down', 'down'  , 'down' , 'down' , 'down', 'down', 'down', 'down', 'down', 'left'],
    ['right', 'down' , 'down' , 'down' , 'down', 'down', 'down', 'down', 'left', 'left'],
    ['right', 'right', 'down' , 'down' , 'down', 'down', 'down', 'left', 'left', 'left'],
    ['right', 'right', 'right', 'down' , 'down', 'down', 'left', 'left', 'left', 'left'],
    ['right', 'right', 'right', 'right', 'exit', 'left', 'left', 'left', 'left', 'left'],
    ['right', 'right', 'right', 'right', 'up'  , 'up'  , 'left', 'left', 'left', 'left'],
    ['right', 'right', 'right', 'up'   , 'up'  , 'up'  , 'up'  , 'left', 'left', 'left'],
    ['right', 'right', 'up'   , 'up'   , 'up'  , 'up'  , 'up'  , 'up'  , 'left', 'left'],
    ['right', 'up'   , 'up'   , 'up'   , 'up'  , 'up'  , 'up'  , 'up'  , 'up'  , 'left'],
    ['up'   , 'up'   , 'up'   , 'up'   , 'up'  , 'up'  , 'up'  , 'up'  , 'up'  , 'up'  ]
]

utility_map = []

positive_reward_position_row = 4
positive_reward_position_col = 4

rows = len(policy)
cols = len(policy[0]) 


one_step_reward = -0.04
function_approximation()

view_utility_map()


[[0.40748754 0.46576403 0.51747957 0.56009894 0.59122692 0.60983164 0.61694496 0.61496211 0.60641833 0.59332651]
 [0.46544688 0.52883543 0.5861066  0.63351955 0.66663996 0.68325224 0.68557199 0.67803352 0.66437766 0.6469786 ]
 [0.51684527 0.58578945 0.65018332 0.70517934 0.74205301 0.75491203 0.74964872 0.73498754 0.71577606 0.69420224]
 [0.5591475  0.63288525 0.70486219 0.77153121 0.81746606 0.82126391 0.80432758 0.78208334 0.75807828 0.73330589]
 [0.58995832 0.66568852 0.74141871 0.81714891 0.8928791  0.8668816  0.84088411 0.81488661 0.78888911 0.76289161]
 [0.6082459  0.68198365 0.75396059 0.82062961 0.86656446 0.87036231 0.85342598 0.83118174 0.80717668 0.78240429]
 [0.61504207 0.68398625 0.74838012 0.80337614 0.84024981 0.85310883 0.84784551 0.83318434 0.81397285 0.79239904]
 [0.61274208 0.67613063 0.7334018  0.78081475 0.81393516 0.83054744 0.83286719 0.82532872 0.81167286 0.7942738 ]
 [0.60388114 0.66215762 0.71387317 0.75649254 0.78762051 0.80622524 0.81333856 0.81135571 0.8028