In [1]:
from random import randint
from random import random
from random import seed
import numpy as np

In [2]:
alpha = float(0.0001)
epsilon = float(0.1)
gamma = float(0.8)
numTraining = int(20)
w = [0.5,0.2, 0.1]

In [3]:
#this function get the next row and colume based on the policy with probability 0.8
#and perpendicular on the policy with probability 0.2

#if the function will take the perpendicular direction
#it will choose the either of the two perpendicular direction on 50% probability
def get_next_r_c(r, c):
    prob = random()
    #80% of the time will take the policy action
    if prob <= 0.8: 
        if policy[r][c] == 'up':
            rnext = r - 1
            cnext = c
        elif policy[r][c] == 'left':
            rnext = r
            cnext = c - 1
        elif policy[r][c] == 'right':
            rnext = r
            cnext = c + 1
        elif policy[r][c] == 'down':
            rnext = r + 1
            cnext = c
            
    #20% of the time will make a perpendiclar action on the policy action
    else:
        if policy[r][c] == 'up' or policy[r][c] == 'down':
            prob2 = random()
            if prob2>0.5:
                #left
                rnext = r
                cnext = c - 1
            else:
                #right
                rnext = r
                cnext = c + 1
                
        elif policy[r][c] == 'right' or policy[r][c] == 'left':
            prob2 = random()
            if prob2>0.5:
                #up
                rnext = r - 1
                cnext = c
            else:
                #down
                rnext = r + 1
                cnext = c
                
    return rnext, cnext

In [4]:
def recursive_approximation(r, c):
    #updates delta values recursively for each step
    if policy[r][c] == 'exit':
        if positive_reward_position_row == r and positive_reward_position_col == c:
            return 1
        else:
            return -1
    
    rnext, cnext = get_next_r_c(r, c)
    
    while rnext >= rows or rnext < 0 or cnext >= cols or cnext < 0 or policy[rnext][cnext] == 'obstacle':
        rnext, cnext = get_next_r_c(r, c)
    
    value = recursive_approximation(rnext,cnext) + one_step_reward
    delta_rule(r,c, value)
    return value

In [5]:
def approximate_value(r,c):
    return w[0]+w[1]*c+w[2]*r

In [6]:
def delta_rule(r,c, current_observed_value):
        w[0] = w[0] + alpha * (current_observed_value - approximate_value(r,c))
        w[1] = w[1] + alpha * (current_observed_value - approximate_value(r,c)) * c
        w[2] = w[2] + alpha * (current_observed_value - approximate_value(r,c)) * r

In [7]:
def function_approximation():
    for i in range(iterations):
        r = randint(0, rows - 1)
        c = randint(0, cols - 1)
        while policy[r][c] == 'obstacle' or policy[r][c] == 'exit':
            r = randint(0, rows - 1)
            c = randint(0, cols - 1)
        recursive_approximation(r, c)



In [8]:
def view_utility_map():
    utility_map = np.zeros((rows,cols))
    for r in range(rows):
        for c in range(cols):
            utility_map[r,c] = w[0]+w[1]*c+w[2]*r
    print(utility_map)

In [9]:
iterations = 10000
w = [0.5,0.2, 0.1]
#should be read it from outside file
policy = [
    ['right', 'right',    'right', 'exit'],
    ['up',    'obstacle', 'up',    'exit'],
    ['up',    'left',     'up',  'left']
]
utility_map = []
positive_reward_position_row = 0
positive_reward_position_col = 3
negative_reward_position_row = 1
negative_reward_position_col = 3
rows = len(policy)
cols = len(policy[0]) 
one_step_reward = -0.04
function_approximation()
view_utility_map()

# print(w)

[[0.72931206 0.79027713 0.85124219 0.91220726]
 [0.67781507 0.73878014 0.79974521 0.86071027]
 [0.62631809 0.68728315 0.74824822 0.80921329]]


In [10]:
iterations = 10000
w = [0.5,0.2, 0.1]
policy = [
    ['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'exit' ],
    ['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'up'   ],
    ['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'up'   , 'up'   ],
    ['right', 'right', 'right', 'right', 'right', 'right', 'right', 'up',    'up'   , 'up'   ],
    ['right', 'right', 'right', 'right', 'right', 'right', 'up'   , 'up',    'up'   , 'up'   ],
    ['right', 'right', 'right', 'right', 'right', 'up'   , 'up'   , 'up',    'up'   , 'up'   ],
    ['right', 'right', 'right', 'right', 'up'   , 'up'   , 'up'   , 'up',    'up'   , 'up'   ],
    ['right', 'right', 'right', 'up'   , 'up'   , 'up'   , 'up'   , 'up',    'up'   , 'up'   ],
    ['right', 'right', 'up'   , 'up'   , 'up'   , 'up'   , 'up'   , 'up',    'up'   , 'up'   ],
    ['right', 'up',    'up'   , 'up'   , 'up'   , 'up'   , 'up'   , 'up',    'up'   , 'up'   ]
]
utility_map = []

positive_reward_position_row = 0
positive_reward_position_col = 9

rows = len(policy)
cols = len(policy[0]) 


one_step_reward = -0.04
function_approximation()

view_utility_map()


[[0.50551841 0.55738227 0.60924612 0.66110998 0.71297384 0.76483769
  0.81670155 0.86856541 0.92042926 0.97229312]
 [0.45346813 0.50533198 0.55719584 0.6090597  0.66092355 0.71278741
  0.76465127 0.81651512 0.86837898 0.92024284]
 [0.40141784 0.4532817  0.50514555 0.55700941 0.60887327 0.66073712
  0.71260098 0.76446484 0.81632869 0.86819255]
 [0.34936756 0.40123141 0.45309527 0.50495913 0.55682298 0.60868684
  0.6605507  0.71241455 0.76427841 0.81614227]
 [0.29731727 0.34918113 0.40104499 0.45290884 0.5047727  0.55663656
  0.60850041 0.66036427 0.71222813 0.76409198]
 [0.24526699 0.29713085 0.3489947  0.40085856 0.45272241 0.50458627
  0.55645013 0.60831398 0.66017784 0.7120417 ]
 [0.1932167  0.24508056 0.29694442 0.34880827 0.40067213 0.45253599
  0.50439984 0.5562637  0.60812756 0.65999141]
 [0.14116642 0.19303028 0.24489413 0.29675799 0.34862185 0.4004857
  0.45234956 0.50421342 0.55607727 0.60794113]
 [0.08911614 0.14097999 0.19284385 0.2447077  0.29657156 0.34843542
  0.40029927 

In [11]:
iterations = 10000
w = [0.5,0.2, 0.1]
policy = [
    ['down', 'down'  , 'down' , 'down' , 'down', 'down', 'down', 'down', 'down', 'left'],
    ['right', 'down' , 'down' , 'down' , 'down', 'down', 'down', 'down', 'left', 'left'],
    ['right', 'right', 'down' , 'down' , 'down', 'down', 'down', 'left', 'left', 'left'],
    ['right', 'right', 'right', 'down' , 'down', 'down', 'left', 'left', 'left', 'left'],
    ['right', 'right', 'right', 'right', 'exit', 'left', 'left', 'left', 'left', 'left'],
    ['right', 'right', 'right', 'right', 'up'  , 'up'  , 'left', 'left', 'left', 'left'],
    ['right', 'right', 'right', 'up'   , 'up'  , 'up'  , 'up'  , 'left', 'left', 'left'],
    ['right', 'right', 'up'   , 'up'   , 'up'  , 'up'  , 'up'  , 'up'  , 'left', 'left'],
    ['right', 'up'   , 'up'   , 'up'   , 'up'  , 'up'  , 'up'  , 'up'  , 'up'  , 'left'],
    ['up'   , 'up'   , 'up'   , 'up'   , 'up'  , 'up'  , 'up'  , 'up'  , 'up'  , 'up'  ]
]

utility_map = []

positive_reward_position_row = 4
positive_reward_position_col = 4

rows = len(policy)
cols = len(policy[0]) 


one_step_reward = -0.04
function_approximation()

view_utility_map()


[[0.6692209  0.68478903 0.70035715 0.71592527 0.73149339 0.74706151
  0.76262964 0.77819776 0.79376588 0.809334  ]
 [0.68726221 0.70283033 0.71839845 0.73396657 0.7495347  0.76510282
  0.78067094 0.79623906 0.81180719 0.82737531]
 [0.70530351 0.72087163 0.73643975 0.75200788 0.767576   0.78314412
  0.79871224 0.81428037 0.82984849 0.84541661]
 [0.72334481 0.73891294 0.75448106 0.77004918 0.7856173  0.80118543
  0.81675355 0.83232167 0.84788979 0.86345791]
 [0.74138612 0.75695424 0.77252236 0.78809048 0.80365861 0.81922673
  0.83479485 0.85036297 0.8659311  0.88149922]
 [0.75942742 0.77499554 0.79056367 0.80613179 0.82169991 0.83726803
  0.85283615 0.86840428 0.8839724  0.89954052]
 [0.77746872 0.79303685 0.80860497 0.82417309 0.83974121 0.85530934
  0.87087746 0.88644558 0.9020137  0.91758183]
 [0.79551003 0.81107815 0.82664627 0.84221439 0.85778252 0.87335064
  0.88891876 0.90448688 0.92005501 0.93562313]
 [0.81355133 0.82911945 0.84468758 0.8602557  0.87582382 0.89139194
  0.90696007