In [1]:
from random import randint
from random import random
from random import seed
import numpy as np

In [2]:
alpha = float(0.0001)
epsilon = float(0.1)
gamma = float(0.8)
numTraining = int(20)
w = [0.5,0.2, 0.1]


In [3]:
def get_next_r_c(r, c):
    prob = random()
    #80% of the time will take the policy action
    if prob <= 0.8: 
        if policy[r][c] == 'up':
            rnext = r - 1
            cnext = c
        elif policy[r][c] == 'left':
            rnext = r
            cnext = c - 1
        elif policy[r][c] == 'right':
            rnext = r
            cnext = c + 1
        elif policy[r][c] == 'down':
            rnext = r + 1
            cnext = c
            
    #20% of the time will make a perpendiclar action on the policy action
    else:
        if policy[r][c] == 'up' or policy[r][c] == 'down':
            prob2 = random()
            if prob2>0.5:
                #left
                rnext = r
                cnext = c - 1
            else:
                #right
                rnext = r
                cnext = c + 1
                
        elif policy[r][c] == 'right' or policy[r][c] == 'left':
            prob2 = random()
            if prob2>0.5:
                #up
                rnext = r - 1
                cnext = c
            else:
                #down
                rnext = r + 1
                cnext = c
                
    return rnext, cnext

In [41]:
def observed_value(r, c):
    if policy[r][c] == 'exit':
        if positive_reward_position_row == r and positive_reward_position_col == c:
            return 1
        else:
            return -1
    
    rnext, cnext = get_next_r_c(r, c)
    
    while rnext >= rows or rnext < 0 or cnext >= cols or cnext < 0 or policy[rnext][cnext] == 'obstacle':
        rnext, cnext = get_next_r_c(r, c)
    
    value = observed_value(rnext,cnext) + one_step_reward
    
    return value

In [42]:
def approximate_value(r,c):
    return w[0]+w[1]*c+w[2]*r

In [43]:
def delta_rule():
    for i in range(iterations):
        r = randint(0, rows - 1)
        c = randint(0, cols - 1)
        while policy[r][c] == 'obstacle' or policy[r][c] == 'exit':
            r = randint(0, rows - 1)
            c = randint(0, cols - 1)
        w[0] = w[0] + alpha * (observed_value(r, c) - approximate_value(r,c))
        w[1] = w[1] + alpha * (observed_value(r, c) - approximate_value(r,c)) * c
        w[2] = w[2] + alpha * (observed_value(r, c) - approximate_value(r,c)) * r


In [44]:
def view_utility_map():
    utility_map = np.zeros((rows,cols))
    for r in range(rows):
        for c in range(cols):
            utility_map[r,c] = w[0]+w[1]*c+w[2]*r
    print(utility_map)

In [101]:
iterations = 30000
w = [0.5,0.2, 0.1]
#should be read it from outside file
policy = [
    ['right', 'right',    'right', 'exit'],
    ['up',    'obstacle', 'up',    'exit'],
    ['up',    'left',     'up',  'left']
]
utility_map = []
positive_reward_position_row = 0
positive_reward_position_col = 3
negative_reward_position_row = 1
negative_reward_position_col = 3
rows = len(policy)
cols = len(policy[0]) 
one_step_reward = -0.04
delta_rule()
view_utility_map()

# print(w)

[[0.6920152  0.69713246 0.70224972 0.70736698]
 [0.66197204 0.6670893  0.67220656 0.67732382]
 [0.63192888 0.63704614 0.6421634  0.64728066]]


In [85]:
iterations = 10000
w = [0.5,0.2, 0.1]
policy = [
    ['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'exit' ],
    ['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'up'   ],
    ['right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'up'   , 'up'   ],
    ['right', 'right', 'right', 'right', 'right', 'right', 'right', 'up',    'up'   , 'up'   ],
    ['right', 'right', 'right', 'right', 'right', 'right', 'up'   , 'up',    'up'   , 'up'   ],
    ['right', 'right', 'right', 'right', 'right', 'up'   , 'up'   , 'up',    'up'   , 'up'   ],
    ['right', 'right', 'right', 'right', 'up'   , 'up'   , 'up'   , 'up',    'up'   , 'up'   ],
    ['right', 'right', 'right', 'up'   , 'up'   , 'up'   , 'up'   , 'up',    'up'   , 'up'   ],
    ['right', 'right', 'up'   , 'up'   , 'up'   , 'up'   , 'up'   , 'up',    'up'   , 'up'   ],
    ['right', 'up',    'up'   , 'up'   , 'up'   , 'up'   , 'up'   , 'up',    'up'   , 'up'   ]
]
utility_map = []

positive_reward_position_row = 0
positive_reward_position_col = 9

rows = len(policy)
cols = len(policy[0]) 


one_step_reward = -0.04
delta_rule()

view_utility_map()


[[0.48469782 0.54100765 0.59731749 0.65362733 0.70993717 0.766247
  0.82255684 0.87886668 0.93517652 0.99148635]
 [0.43779919 0.49410903 0.55041887 0.6067287  0.66303854 0.71934838
  0.77565822 0.83196805 0.88827789 0.94458773]
 [0.39090057 0.44721041 0.50352024 0.55983008 0.61613992 0.67244976
  0.72875959 0.78506943 0.84137927 0.89768911]
 [0.34400195 0.40031178 0.45662162 0.51293146 0.5692413  0.62555113
  0.68186097 0.73817081 0.79448065 0.85079048]
 [0.29710332 0.35341316 0.409723   0.46603283 0.52234267 0.57865251
  0.63496235 0.69127218 0.74758202 0.80389186]
 [0.2502047  0.30651454 0.36282437 0.41913421 0.47544405 0.53175389
  0.58806372 0.64437356 0.7006834  0.75699324]
 [0.20330607 0.25961591 0.31592575 0.37223559 0.42854542 0.48485526
  0.5411651  0.59747494 0.65378477 0.71009461]
 [0.15640745 0.21271729 0.26902713 0.32533696 0.3816468  0.43795664
  0.49426648 0.55057631 0.60688615 0.66319599]
 [0.10950883 0.16581866 0.2221285  0.27843834 0.33474818 0.39105801
  0.44736785 0

In [60]:
iterations = 1000
w = [0.5,0.2, 0.1]
policy = [
    ['down', 'down'  , 'down' , 'down' , 'down', 'down', 'down', 'down', 'down', 'left'],
    ['right', 'down' , 'down' , 'down' , 'down', 'down', 'down', 'down', 'left', 'left'],
    ['right', 'right', 'down' , 'down' , 'down', 'down', 'down', 'left', 'left', 'left'],
    ['right', 'right', 'right', 'down' , 'down', 'down', 'left', 'left', 'left', 'left'],
    ['right', 'right', 'right', 'right', 'exit', 'left', 'left', 'left', 'left', 'left'],
    ['right', 'right', 'right', 'right', 'up'  , 'up'  , 'left', 'left', 'left', 'left'],
    ['right', 'right', 'right', 'up'   , 'up'  , 'up'  , 'up'  , 'left', 'left', 'left'],
    ['right', 'right', 'up'   , 'up'   , 'up'  , 'up'  , 'up'  , 'up'  , 'left', 'left'],
    ['right', 'up'   , 'up'   , 'up'   , 'up'  , 'up'  , 'up'  , 'up'  , 'up'  , 'left'],
    ['up'   , 'up'   , 'up'   , 'up'   , 'up'  , 'up'  , 'up'  , 'up'  , 'up'  , 'up'  ]
]

utility_map = []

positive_reward_position_row = 4
positive_reward_position_col = 4

rows = len(policy)
cols = len(policy[0]) 


one_step_reward = -0.04
delta_rule()

view_utility_map()


[[0.48174875 0.52618547 0.5706222  0.61505892 0.65949565 0.70393237
  0.7483691  0.79280582 0.83724255 0.88167928]
 [0.48362329 0.52806001 0.57249674 0.61693346 0.66137019 0.70580691
  0.75024364 0.79468037 0.83911709 0.88355382]
 [0.48549783 0.52993455 0.57437128 0.61880801 0.66324473 0.70768146
  0.75211818 0.79655491 0.84099163 0.88542836]
 [0.48737237 0.5318091  0.57624582 0.62068255 0.66511927 0.709556
  0.75399272 0.79842945 0.84286617 0.8873029 ]
 [0.48924691 0.53368364 0.57812036 0.62255709 0.66699381 0.71143054
  0.75586726 0.80030399 0.84474071 0.88917744]
 [0.49112145 0.53555818 0.5799949  0.62443163 0.66886835 0.71330508
  0.7577418  0.80217853 0.84661525 0.89105198]
 [0.49299599 0.53743272 0.58186944 0.62630617 0.67074289 0.71517962
  0.75961634 0.80405307 0.84848979 0.89292652]
 [0.49487053 0.53930726 0.58374398 0.62818071 0.67261743 0.71705416
  0.76149088 0.80592761 0.85036434 0.89480106]
 [0.49674507 0.5411818  0.58561852 0.63005525 0.67449197 0.7189287
  0.76336543 0.